name: proyek_akhir_tpm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.12
  hive_generator: ^1.1.0
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  encrypt: ^5.0.3
  image_picker: ^1.1.1
  permission_handler: ^10.2.0
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
